spring:
  application:
    name: main-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

rest:
  client:
    parsing:
      base-url: http://error-parser:8001
    clustering:
      base-url: http://cluster-service:8002
    llm:
      base-url: http://opto-llm-parser:8000



springdoc:
  swagger-ui:
    path: /docs
