spring:
  application:
    name: main-service
  datasource:
    url: jdbc:postgresql://localhost:5432/errorhack
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop

rest:
  client:
    parsing:
      base-url: http://localhost:8001
    clustering:
      base-url: http://localhost:8002

springdoc:
  swagger-ui:
    path: /docs
